/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AccountDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;
/**
 *
 * @author cestdrama
 */
public class AccMngPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccMngAreaPanel
     */
    private JPanel userProcessContainer; 
    private AccountDirectory accDir;
    AccMngPanel(JPanel userProcessContainer, AccountDirectory accDir) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.accDir=accDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccBTN = new javax.swing.JButton();
        mngAccBTN = new javax.swing.JButton();

        createAccBTN.setText("Create Account");
        createAccBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBTNActionPerformed(evt);
            }
        });

        mngAccBTN.setText("Manage Account");
        mngAccBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngAccBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createAccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mngAccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(createAccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mngAccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBTNActionPerformed
        // TODO add your handling code here:
        CreateAccPanel panel=new CreateAccPanel(userProcessContainer,accDir); 
        userProcessContainer.add("CreateAccPanel",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createAccBTNActionPerformed

    private void mngAccBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngAccBTNActionPerformed
        // TODO add your handling code here:
        ManageAccPanel panel=new ManageAccPanel(userProcessContainer,accDir);
        userProcessContainer.add("ManageAccPanel",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngAccBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccBTN;
    private javax.swing.JButton mngAccBTN;
    // End of variables declaration//GEN-END:variables
}
