/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

/**
 *
 * @author cestdrama
 */
public class createJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    private Product product;
    private Supplier suplier;
    public createJPanel(Product product) {
        initComponents();
        this.product=product;
        //suplier=new Supplier();
        //suplier=product.setSuplier(suplier);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxtf = new javax.swing.JTextField();
        priceTxtf = new javax.swing.JTextField();
        descriptionTxtf = new javax.swing.JTextField();
        availNumTxtf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        supnameTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supaddTXT = new javax.swing.JTextField();

        jLabel4.setText("Avalibility Number:");

        jLabel3.setText("price:");

        jLabel2.setText("name:");

        jLabel5.setText("Description:");

        nameTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtfActionPerformed(evt);
            }
        });

        priceTxtf.setText(" ");
        priceTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtfActionPerformed(evt);
            }
        });

        descriptionTxtf.setText(" ");
        descriptionTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTxtfActionPerformed(evt);
            }
        });

        availNumTxtf.setText(" ");
        availNumTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTxtfActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Create your record");

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Supplier Name:");

        supnameTXT.setText(" ");
        supnameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnameTXTActionPerformed(evt);
            }
        });

        jLabel8.setText("Supplier Address:");

        supaddTXT.setText(" ");
        supaddTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supaddTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTxtf)
                                    .addComponent(priceTxtf, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(availNumTxtf)
                                    .addComponent(supnameTXT)
                                    .addComponent(descriptionTxtf)
                                    .addComponent(supaddTXT)))
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(CreateButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priceTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(availNumTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descriptionTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(supaddTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtfActionPerformed

    private void priceTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtfActionPerformed

    private void descriptionTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTxtfActionPerformed

    private void availNumTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTxtfActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:

        //binding the user input to the product object
        product.setName(nameTxtf.getText());
        product.setPrice(priceTxtf.getText());
        product.setAvialNum(availNumTxtf.getText());
        product.setDescription(descriptionTxtf.getText());
        
        suplier= new Supplier();
        suplier.setSupplierName(supnameTXT.getText());
        suplier.setAddress(supaddTXT.getText());
        product.setSuplier(suplier);
            
        //prompt user that product was successfully created
        JOptionPane.showMessageDialog(null,"your record have benn successfully created!");
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void supnameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnameTXTActionPerformed

    private void supaddTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supaddTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supaddTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField availNumTxtf;
    private javax.swing.JTextField descriptionTxtf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTxtf;
    private javax.swing.JTextField priceTxtf;
    private javax.swing.JTextField supaddTXT;
    private javax.swing.JTextField supnameTXT;
    // End of variables declaration//GEN-END:variables
}
