/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

/**
 *
 * @author cestdrama
 */
public class updateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form updateJPanel
     */
    private Product product;
    private Supplier suplier;
    public updateJPanel(Product product) {
        initComponents();
        this.product=product;
        nameTxtf.setText(product.getName());
        priceTxtf.setText(product.getPrice());
        availNumTxtf.setText(product.getAvialNum());
        descriptionTxtf.setText(product.getDescription());
        Supplier s=product.getSuplier();
        supnameTXT.setText(s.getSupplierName());
        supaddTXT.setText(s.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        supnameTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceTxtf = new javax.swing.JTextField();
        descriptionTxtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameTxtf = new javax.swing.JTextField();
        availNumTxtf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        supaddTXT = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE");

        jLabel8.setText("Supplier Address::");

        supnameTXT.setText(" ");
        supnameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnameTXTActionPerformed(evt);
            }
        });

        jLabel7.setText("Supplier Name:");

        priceTxtf.setText(" ");
        priceTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtfActionPerformed(evt);
            }
        });

        descriptionTxtf.setText(" ");
        descriptionTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTxtfActionPerformed(evt);
            }
        });

        jLabel5.setText("Description:");

        nameTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtfActionPerformed(evt);
            }
        });

        availNumTxtf.setText(" ");
        availNumTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTxtfActionPerformed(evt);
            }
        });

        jLabel4.setText("Avalibility Number:");

        jLabel2.setText("name:");

        jLabel3.setText("price:");

        supaddTXT.setText(" ");
        supaddTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supaddTXTActionPerformed(evt);
            }
        });

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(updateButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceTxtf, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(nameTxtf)
                            .addComponent(availNumTxtf)
                            .addComponent(descriptionTxtf)
                            .addComponent(supaddTXT)
                            .addComponent(supnameTXT))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priceTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(availNumTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descriptionTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(supnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supaddTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addComponent(updateButton)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supnameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnameTXTActionPerformed

    private void priceTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtfActionPerformed

    private void descriptionTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTxtfActionPerformed

    private void nameTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtfActionPerformed

    private void availNumTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTxtfActionPerformed

    private void supaddTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supaddTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supaddTXTActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        product.setName(nameTxtf.getText());
        product.setPrice(priceTxtf.getText());
        product.setAvialNum(availNumTxtf.getText());
        product.setDescription(descriptionTxtf.getText());
        
        suplier= new Supplier();
        suplier.setSupplierName(supnameTXT.getText());
        suplier.setAddress(supaddTXT.getText());
        product.setSuplier(suplier);
        
        //prompt user that product was successfully cupdated
        JOptionPane.showMessageDialog(null,"your record have benn successfully updated!");
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availNumTxtf;
    private javax.swing.JTextField descriptionTxtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTxtf;
    private javax.swing.JTextField priceTxtf;
    private javax.swing.JTextField supaddTXT;
    private javax.swing.JTextField supnameTXT;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
