/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
/**
 *
 * @author cestdrama
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private Product product;
    private Supplier suplier;
    public ViewJPanel(Product product) {
        initComponents();
        this.product=product;
        displayProduct();
    }
    
    //
    private void displayProduct(){
        nameTxtf.setText(product.getName());
        priceTxtf.setText(product.getPrice());
        availNumTxtf.setText(product.getAvialNum());
        descriptionTxtf.setText(product.getDescription());
        Supplier s=product.getSuplier();
        supnameTXT.setText(s.getSupplierName());
        supaddTXT.setText(s.getAddress());
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        availNumTxtf = new javax.swing.JTextField();
        priceTxtf = new javax.swing.JTextField();
        nameTxtf = new javax.swing.JTextField();
        descriptionTxtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supnameTXT = new javax.swing.JTextField();
        supaddTXT = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(390, 415));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("View your record");

        jLabel4.setText("Avalibility Number:");

        availNumTxtf.setText(" ");
        availNumTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTxtfActionPerformed(evt);
            }
        });

        priceTxtf.setText(" ");
        priceTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtfActionPerformed(evt);
            }
        });

        nameTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtfActionPerformed(evt);
            }
        });

        descriptionTxtf.setText(" ");
        descriptionTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTxtfActionPerformed(evt);
            }
        });

        jLabel3.setText("price:");

        jLabel5.setText("Description:");

        jLabel2.setText("name:");

        jLabel6.setText("Supplier Name:");

        jLabel7.setText("Supplier Address:");

        supnameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnameTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descriptionTxtf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(availNumTxtf)
                            .addComponent(priceTxtf)
                            .addComponent(nameTxtf)
                            .addComponent(supnameTXT)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supaddTXT)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priceTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(availNumTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descriptionTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(supnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(supaddTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void availNumTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTxtfActionPerformed

    private void priceTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtfActionPerformed

    private void nameTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtfActionPerformed

    private void descriptionTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTxtfActionPerformed

    private void supnameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnameTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availNumTxtf;
    private javax.swing.JTextField descriptionTxtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTxtf;
    private javax.swing.JTextField priceTxtf;
    private javax.swing.JTextField supaddTXT;
    private javax.swing.JTextField supnameTXT;
    // End of variables declaration//GEN-END:variables
}
