/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirliners;

import Business.*;
import javax.swing.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author cestdrama
 */
public class CreateNewAirlinersPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinersPanel
     */
    private JPanel CardSecePanel; 
    private ManageAirlinersPanel manageAirlinersPanel;
    private AirlinersDirectory airlDir;
    private Airliners airl;
    CreateNewAirlinersPanel(ManageAirlinersPanel manageAirlinersPanel, JPanel CardSecePanel, AirlinersDirectory airlDir) {
        initComponents();
        this.CardSecePanel=CardSecePanel;
        this.airlDir=airlDir;
        this.manageAirlinersPanel = manageAirlinersPanel;
    }
   
    public JButton getCreateairlBTN() {
        return createairlBTN;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        airlnameTXT = new javax.swing.JTextField();
        createairlBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addressTXT = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        jLabel1.setText("Create Airliners");

        jLabel2.setText("Airliners Name:");

        createairlBTN.setText("Ok");
        createairlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createairlBTNActionPerformed(evt);
            }
        });

        backBTN.setText("<<Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        jLabel3.setText("Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airlnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(createairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(airlnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createairlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createairlBTNActionPerformed
        // TODO add your handling code here:
        System.out.println("Create");
        String name=airlnameTXT.getText();
        String address=addressTXT.getText();
        
        Airliners airl=airlDir.addairl();
        airl.setAirlinersname(name);
        airl.setAddress(address);
        JOptionPane.showMessageDialog(null,"New Airliners has been successfully created!");
        airlnameTXT.setText("");
        addressTXT.setText("");
        
        //
        CardSecePanel.remove(this);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.previous(CardSecePanel);
        
        this.manageAirlinersPanel.populateTable();
    }//GEN-LAST:event_createairlBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        CardSecePanel.remove(this);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.previous(CardSecePanel);
    }//GEN-LAST:event_backBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTXT;
    private javax.swing.JTextField airlnameTXT;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton createairlBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
