/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirliners;

import Business.*;
import javax.swing.JPanel;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cestdrama
 */
public class ManageAirlinersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersPanel
     */
    
    private JPanel CardSecePanel;
    private AirlinersDirectory airlDir;
    public ManageAirlinersPanel(JPanel CardSecePanel, AirlinersDirectory airlDir) {
       initComponents();
       this.CardSecePanel=CardSecePanel;
       this.airlDir=airlDir;
       populateTable();
    }
    
    //
    public void populateTable(){
        //Clear airliner table 
        //System.out.println("Populate");
        DefaultTableModel dtm=(DefaultTableModel)TBLmngairl.getModel();
        dtm.setRowCount(0);
        //System.out.println(airlDir.getAirlinersList().size());
        for(Airliners airl:airlDir.getAirlinersList()){
            Object[] row=new Object[2];
            row[0]=airl;
            row[1]=airl.getAddress();
            //JOptionPane.showMessageDialog(null,row[0]);       
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewairlBTN = new javax.swing.JButton();
        createairlBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLmngairl = new javax.swing.JTable();
        backBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        jLabel1.setText("Manage Airliners");

        viewairlBTN.setText("View/Update");
        viewairlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewairlBTNActionPerformed(evt);
            }
        });

        createairlBTN.setText("Create Airliners");
        createairlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createairlBTNActionPerformed(evt);
            }
        });

        TBLmngairl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLmngairl);

        backBTN.setText("<<Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(createairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(backBTN)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewairlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewairlBTNActionPerformed
        // TODO add your handling code here:
        int row = TBLmngairl.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Airliners airl = (Airliners)TBLmngairl.getValueAt(row,0);
        ViewAirlinersPanel panel = new ViewAirlinersPanel(this,CardSecePanel, airl);
        CardSecePanel.add("ViewAirlinersPanel", panel);
        CardLayout layout = (CardLayout)CardSecePanel.getLayout();
        layout.next(CardSecePanel);
        
    }//GEN-LAST:event_viewairlBTNActionPerformed

    private void createairlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createairlBTNActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinersPanel panel=new CreateNewAirlinersPanel(this, CardSecePanel,airlDir); 
        CardSecePanel.add("CreateAccPanel",panel);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.next(CardSecePanel);
    }//GEN-LAST:event_createairlBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        CardSecePanel.remove(this);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.previous(CardSecePanel);    
    }//GEN-LAST:event_backBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        int selerow=TBLmngairl.getSelectedRow();
        if (selerow>=0){
            int dialogButton=JOptionPane.YES_NO_OPTION;
            int dialogResult=JOptionPane.showConfirmDialog(null,"Would you like to delete this airliner?","WARNING",dialogButton);
            if(dialogResult==JOptionPane.YES_OPTION){
                Airliners airl=(Airliners) TBLmngairl.getValueAt(selerow,0);
                airlDir.deleteairl(airl);
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row you want to delete!","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLmngairl;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton createairlBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewairlBTN;
    // End of variables declaration//GEN-END:variables
}
