/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import Interface.ManageAirliners.*;
import Interface.ManageFlights.*;
import Interface.ManageCustomer.*;
import Business.*;
import javax.swing.JOptionPane;

/**
 *
 * @author cestdrama
 */
public class TraAgcMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form TraAgcMainFrame
     */
    private TravelAgency travelagency;
    //private AirlinersDirectory airlDir;
    public TraAgcMainFrame() {
        initComponents();
        WelcomePanel panel = new WelcomePanel();
        CardSecePanel.add("WelcomePanel",panel);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.next(CardSecePanel);
        //airlDir=new AirlinersDirectory();
        travelagency=new TravelAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        CardSecePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        mngcusBTN = new javax.swing.JButton();
        mngairlBTN = new javax.swing.JButton();
        mngFlightBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CardSecePanel.setBackground(new java.awt.Color(255, 255, 255));
        CardSecePanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(CardSecePanel);

        mngcusBTN.setText("Manage Customer");
        mngcusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngcusBTNActionPerformed(evt);
            }
        });

        mngairlBTN.setText("Manage Airlines");
        mngairlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngairlBTNActionPerformed(evt);
            }
        });

        mngFlightBTN.setText("Manage Flight");
        mngFlightBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngFlightBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mngcusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mngairlBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(mngFlightBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(mngairlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(mngFlightBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(mngcusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mngcusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngcusBTNActionPerformed
        // TODO add your handling code here:
        AirlinersDirectory airlDir = travelagency.getAirldir();
        CustomerDirectory cusDir = travelagency.getCusdir();
        //JOptionPane.showMessageDialog(null,airlDir);
        
        ManageCusPanel panel = new ManageCusPanel(CardSecePanel,travelagency,cusDir);
        CardSecePanel.add("ManageAirlinersPanel",panel);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.next(CardSecePanel);
    }//GEN-LAST:event_mngcusBTNActionPerformed

    private void mngairlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngairlBTNActionPerformed
        // TODO add your handling code here:
        AirlinersDirectory airlDir = travelagency.getAirldir();
        //JOptionPane.showMessageDialog(null,airlDir);
        ManageAirlinersPanel panel = new ManageAirlinersPanel(CardSecePanel,airlDir);
        CardSecePanel.add("ManageAirlinersPanel",panel);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.next(CardSecePanel);
        
    }//GEN-LAST:event_mngairlBTNActionPerformed

    private void mngFlightBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngFlightBTNActionPerformed
        // TODO add your handling code here:
        AirlinersDirectory airlDir = travelagency.getAirldir();
        //Airliners airl = airlDir.getAirliners();
        FlightWorkArea panel = new FlightWorkArea(CardSecePanel,airlDir);
        CardSecePanel.add("FlightWorkArea",panel);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.next(CardSecePanel);
    }//GEN-LAST:event_mngFlightBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraAgcMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraAgcMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraAgcMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraAgcMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraAgcMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSecePanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton mngFlightBTN;
    private javax.swing.JButton mngairlBTN;
    private javax.swing.JButton mngcusBTN;
    // End of variables declaration//GEN-END:variables
}
