/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageFlights;

import Business.Airliners;
import Business.Flight;
import Interface.ManageAirliners.ViewAirlinersPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cestdrama
 */
public class FlightFoundPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightFoundPanel
     */
    private JPanel CardSecePanel;
    private ArrayList<Flight> searchlist;
    public FlightFoundPanel(JPanel CardSecePanel,ArrayList<Flight> searchlist) {
        initComponents();
        this.CardSecePanel=CardSecePanel;
        this.searchlist=searchlist;
        System.out.printf("List size: %d\n", searchlist.size());
        refreshTable();
    }
    //
    public void refreshTable(){
        //Clear airliner table 
        System.out.println("Populate");
        DefaultTableModel dtm=(DefaultTableModel)flfoundTBL.getModel();
        dtm.setRowCount(0);
        //System.out.println(airlDir.getAirlinersList().size());
        for(Flight flight:searchlist){
            System.out.println("FOR");
            Object[] row=new Object[4];
            row[0]=flight;
            row[1]=flight.getFromlocaltion();
            row[2]=flight.getTolocation();
            
            Date date=flight.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
            String datestr = sdf.format(date); 
            row[3]=datestr;
            //JOptionPane.showMessageDialog(null,row[0]);       
            dtm.addRow(row);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flfoundTBL = new javax.swing.JTable();
        viewdetailBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        jLabel1.setText("Flights Found");

        flfoundTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flightnum", "Departure", "Arrival", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flfoundTBL);

        viewdetailBTN.setText("View Details");
        viewdetailBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailBTNActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewdetailBTN)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewdetailBTN)
                    .addComponent(jButton1))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetailBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailBTNActionPerformed
        // TODO add your handling code here:
        int row = flfoundTBL.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Flight flight = (Flight)flfoundTBL.getValueAt(row,0);
        ViewFlightdetailPanel panel = new ViewFlightdetailPanel(CardSecePanel, flight);
        CardSecePanel.add("ViewAirlinersPanel", panel);
        CardLayout layout = (CardLayout)CardSecePanel.getLayout();
        layout.next(CardSecePanel);
    }//GEN-LAST:event_viewdetailBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardSecePanel.remove(this);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.previous(CardSecePanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable flfoundTBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewdetailBTN;
    // End of variables declaration//GEN-END:variables
}
