/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomer;

import Business.*;
import Interface.ManageAirliners.CreateNewAirlinersPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cestdrama
 */
public class ManageCusPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCusPanel
     */
    private JPanel CardSecePanel;
    private TravelAgency travelagency;
    private CustomerDirectory cusDir;
    private AirlinersDirectory airlDir;
    public int id=1;
    public ManageCusPanel(JPanel CardSecePanel,TravelAgency travelagency,CustomerDirectory cusDir) {
        initComponents();
        this.CardSecePanel=CardSecePanel;
        this.travelagency=travelagency;
        this.cusDir=cusDir;
        this.airlDir=travelagency.getAirldir();
        populateTable();
    }

    

    //
    private void populateTable(){
        DefaultTableModel dtm=(DefaultTableModel)mngcusTBL.getModel();
        dtm.setRowCount(0);
        for(Customer cus:cusDir.getCustomerList()){
            Object[] row=new Object[2];
            row[0]=cus;
            row[1]=cus.getCusID();
            //JOptionPane.showMessageDialog(null,row[0]);       
            dtm.addRow(row);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mngcusTBL = new javax.swing.JTable();
        addcusBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cusnameTXT = new javax.swing.JTextField();
        bookBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        jLabel1.setText("Manage Customer");

        mngcusTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Customer Name", "Customer ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mngcusTBL);

        addcusBTN.setText("Add Customer");
        addcusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcusBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer Name:");

        bookBTN.setText("Book Tickets>>");
        bookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBTNActionPerformed(evt);
            }
        });

        backBTN.setText("<<Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBTN)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cusnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addcusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bookBTN)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcusBTN)
                    .addComponent(cusnameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(bookBTN))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addcusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcusBTNActionPerformed
        // TODO add your handling code here:
        Customer customer;
        if(cusnameTXT.getText().equals("")){JOptionPane.showMessageDialog(null,"please input a name");}
        else
        {
        customer = cusDir.addcus();
        customer.setFullname(cusnameTXT.getText());
        customer.setCusID(id);
        JOptionPane.showMessageDialog(null,"Customer name been added!");
        populateTable();
        id++;
        }
    }//GEN-LAST:event_addcusBTNActionPerformed

    private void bookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBTNActionPerformed
        // TODO add your handling code here:
        
        int selerow=mngcusTBL.getSelectedRow();
        if(selerow<0){
          JOptionPane.showMessageDialog(null,"Please select a customer you want to book ticket for!","WARNING",JOptionPane.WARNING_MESSAGE);  
        }
        else{
        Customer cus=(Customer) mngcusTBL.getValueAt(selerow,0);
        BooktkPanel panel=new BooktkPanel(CardSecePanel,airlDir); 
        CardSecePanel.add("BooktkPanel",panel);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.next(CardSecePanel);
        }
    }//GEN-LAST:event_bookBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        CardSecePanel.remove(this);
        CardLayout layout=(CardLayout) CardSecePanel.getLayout();
        layout.previous(CardSecePanel);
    }//GEN-LAST:event_backBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcusBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton bookBTN;
    private javax.swing.JTextField cusnameTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mngcusTBL;
    // End of variables declaration//GEN-END:variables
}
